### PR TITLE
minor change in project

### PR DESCRIPTION
**Pull request by FarshidRoohi**
- viewDataBinding HomeFragment
- create BaseFragment
- fixed deprecated method getColor()
- change hardcode string value to resource string
- remove .idea and release folders and add gitIgnore

### CODE REVIEW

**Comment by Tenkei** [comment]
It is not some minor changes, is it? 😆 
Thanks for the effort you put in, I reviewing the PR but I have a feeling it's gonna take some time to merge.

**Comment by Tenkei** [comment]
Hi again, first of all thanks for the code clean up as It was really needed.
Sadly I cannot merge this PR as it is. Almost all of changes help improving readability, but the use of Data-binding not only add complexity but also does not really improve anything. It does remove some findViewById but again those can easily be removed by use of lazyBinding in Kotlin. 

If possible please remove data-binding so I can add this PR as it is, also I can merge this PR but reverting the data-binding commit.

**Comment by FarshidRoohi** [comment]
Thanks for reviewing the code
i did not know that you do not use DataBinding 
i hope that in the future I will be able to participate in this project
because the project is lovely 👍

**Comment by Tenkei** [comment]
You already participating ^^
So can you revert the data-binding or should I merge and revert it?

**Comment by FarshidRoohi** [comment]
I will do and again pull request in project :)

**Pull request closed without merging**
